#
# https://github.com/P3TERX/GeoLite.mmdb
#
# File: .github/workflows/GeoLite.yml
# Description: Publish GeoLite.mmdb
#
# MIT License
#
# Copyright (c) 2021-2024 P3TERX <https://p3terx.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Publish JP IP

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 1 */3 * *

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        sudo curl -Ls https://github.com/ipinfo/mmdbctl/releases/download/mmdbctl-1.4.7/deb.sh | sudo sh
        sudo apt-get install -y jq
        echo "TAG_NAME=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: Download GeoLite2 Database
      run: |
        curl -L -o GeoLite2-Country.mmdb \
        "https://github.com/P3TERX/GeoLite.mmdb/raw/refs/heads/download/GeoLite2-Country.mmdb"

    - name: Export to JSON
      run: mmdbctl export GeoLite2-Country.mmdb -f json --no-header true -o GeoLite2-Country.json

    - name: Process JSON Data
      run: |
        # 提取日本 IPv4 CIDR
        jq -r '
          select(
            (.country?.iso_code? == "JP") or 
            (.registered_country?.iso_code? == "JP")
          ) |
          select(.range | contains(".")) |
          .range
        ' GeoLite2-Country.json | sort -u > jp-cidr.txt

        # 分割文件并创建目录
        mkdir -p upload
        split -d -l 900 jp-cidr.txt upload/jp-list- --additional-suffix=.txt

    - name: Commit to download branch
      run: |
        cd upload
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -b download
        git add .
        git commit -m "Japan CIDR update $(date +'%Y-%m-%d')"
        git remote add origin \
          "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git push -f origin download


    - name: Upload to Releases
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        body: ${{ env.TAG_NAME }}
        files: upload/*.txt

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
